### ISSUE TITLE
Add version pinning for Space ROS repos

### ISSUE THREAD

**Issue by Bckempa** [space-ros/space-ros#101]
Space ROS repos should use version pinning just like upstream packages. This involves a procedural question of how/when to update these versions.

Should develop always build with develop and pinning only added to tagged releases, or should versions always be pinned and each subproject must update their version tag when ready?

**Comment by EzraBrooks** [comment]
Specifically all Space ROS packages need to have static hashes for inclusion instead of branch names

**Comment by EzraBrooks** [comment]
Use same vcs import -> vcs export step as upstream deps

**Comment by xfiderek** [comment]
I can take that after https://github.com/space-ros/docker/pull/90 is closed and next steps for https://github.com/space-ros/docker/issues/88 are clear

**Comment by xfiderek** [comment]
Ok, so the main problem is that build of packages from [spaceros.repos](https://github.com/space-ros/space-ros/blob/main/spaceros.repos) is not reproducible, as vcs entries point to branches instead of commits/tags. I spoke about it with @Bckempa and here are some points which are not 100% clear (at least to me)

1. How dependent packages in spaceros.repos are released with new spaceros release (e.g. process_sarif)? Do we follow the same release cycle and create tags with the same name in dependent repos? What about repos that we don't control (e.g. ament_cobra, ikos)
2. How do we update spaceros.repos file for the release. Do we want to manually specify all the tags / agree on some convention for all packages / script it somehow

3. In case of main branch (non-release), which versions of these packages should be pulled? How the spaceros.repos file should look like. Do we want to point to branches?

@Bckempa @ivanperez-keera @EzraBrooks @mkhansenbot, any thoughts?

**Comment by xfiderek** [comment]
@Bckempa  I think after the discussion from today we are good to close this issue.
