### ISSUE TITLE
Fix ros2.repos update script

### ISSUE THREAD

**Issue by Bckempa** [space-ros/space-ros#98]
During release engineering, the earthly-triggered procedure to update the ros2.repos to the upstream version did not produce any changes in what appears to be an error.

**Comment by EzraBrooks** [comment]
@xfiderek

**Comment by xfiderek** [comment]
I have created a pull request that fixes this particular issue, however I want to discuss several things related to that fix:

1. How frequently we want to update ros2.repos file? Each update of that file poses a risk that some of the packages will no longer conform with standards that we define or introduce bugs. Do we plan to freeze it eventually?
2. Some of the entries in `ros2.repos` refer main branch instead of pointing to specific version (e.g. ament_ikos package). This causes a risk of non-reproducible builds, as version may change. https://github.com/space-ros/space-ros/blob/3cbdef39f7b0183a48720105bb040d1358e5215c/ros2.repos#L15-L18
3. Maybe more general question, but what do we do if external packages do not conform with space-grade requirements? I expect that rclcpp alone to have number of violations, as its not created with that objective in mind.
4. I think i discovered some further issues related to Earthfile in docker repo. I have created a separate issue for that. Please take a look: https://github.com/space-ros/docker/issues/88
